# Generated by Django 4.1.7 on 2023-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст'),
        ),
    ]
